--#SQLite sondagskooldb
/**
--Command	Description
.show	Displays current settings for various parameters
.databases	Provides database names and files
.quit	Quit sqlite3 program
.tables	Show current tables
.schema	Display schema of table
.header	Display or hide the output table header
.mode Select mode for the output table
.dump	Dump database in SQL text format

--cleanup
DELETE FROM tblename;
VACUUM;
**/

--create new tables
CREATE TABLE MEMBERS ( 
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	NAME TEXT NOT NULL,
	SURNAME TEXT NOT NULL,
	EMAIL TEXT,
	CELL TEXT NOT NULL,
	STID TEXT NOT NULL,
	BOOK_COUNT INTEGER NOT NULL
    );

CREATE TABLE USERS ( 
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	USER_NAME TEXT NOT NULL,
	USER_PASSWORD TEXT NOT NULL,
	USER_EMAIL TEXT NOT NULL,
	ACL_ID INTEGER NOT NULL
    );

CREATE TABLE ACL ( 
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	NAME TEXT NOT NULL,
	DESCRIPTION TEXT NOT NULL
    );

CREATE TABLE BOOKS ( 
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	TITLE TEXT NOT NULL,
	AUTHER TEXT NOT NULL,
	EDITION TEXT NOT NULL,
	YEAR TEXT NOT NULL,
	ISBN TEXT NOT NULL,
	PICTURE TEXT NOT NULL
    );

CREATE TABLE BOOK_LOGS ( 
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	BOOK_ID INTEGER NOT NULL,
	MEMBER_ID INTEGER NOT NULL,
	CHECKED_OUT DATE NOT NULL,
    OUT_USER INTEGER NOT NULL,
	CHECKED_IN DATE,
    IN_USER INTEGER
    );

    -- INSERT SOME DATA
INSERT INTO ACL ('NAME','DESCRIPTION') VALUES('SYSTEM_ADMIN','FULLY ADMINISTERS THE SYSTEM');
INSERT INTO ACL ('NAME','DESCRIPTION') VALUES('LIBRARIAN','MANAGES BOOKS AND MEMBERS');
INSERT INTO ACL ('NAME','DESCRIPTION') VALUES('CLERK','DOES BOOK CHECK IN AN CHECK OUT');
INSERT INTO ACL ('NAME','DESCRIPTION') VALUES('GUEST','CAN SEE BOOKS IN STORE');


INSERT INTO USERS ('USER_NAME','USER_PASSWORD','USER_EMAIL','ACL_ID') VALUES('admin','admin','admin@mail.not',1);